Edu_Hutech/Controllers/ReportController.cs
using System.Linq;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using Edu_Hutech.Models;

namespace Edu_Hutech.Controllers
{
    public class ReportController : Controller
    {
        // GET: Report
        HutechEduDataContext db = new HutechEduDataContext();
        public ActionResult Dat_SV5T_Khoa()
        {
            if (Session["Khoa"] == null)
            {
                return Redirect("/UserLogin/UserLogin");
            }
            string makhoa = System.Web.HttpContext.Current.Session["Khoa"].ToString();
            int sl_tc = db.GetTaiLieu_SV5T_TheoCap("K").ToList().Count;
            var dsdk = db.Ds_Dat_SV5T_Khoa(makhoa, sl_tc).ToList();
            return View(dsdk);
        }
        public void ExportToExcel()
        {
            var ds_dk = new System.Data.DataTable("Danh Sách Đạt Sinh Viên 5 Tốt Cấp Khoa");
            ds_dk.Columns.Add("STT", typeof(int));
            ds_dk.Columns.Add("Họ", typeof(string));
            ds_dk.Columns.Add("Tên", typeof(string));
            ds_dk.Columns.Add("MSSV", typeof(string));
            ds_dk.Columns.Add("Lớp", typeof(string));
            ds_dk.Columns.Add("Năm Học", typeof(int));

            string makhoa = System.Web.HttpContext.Current.Session["Khoa"].ToString();
            int sl_tc = db.GetTaiLieu_SV5T_TheoCap("K").ToList().Count;
            var dsdk = db.Ds_Dat_SV5T_Khoa(makhoa, sl_tc).ToList();
            int i = 0;
            int row = 1;
            foreach( var item in dsdk)
            {
                ds_dk.Rows.Add(row,dsdk[i].Ho,dsdk[i].Ten,dsdk[i].MSSV,dsdk[i].MaLop,dsdk[i].NamHoc);                
                row++;
                i++;
            }
            var grid = new GridView();
            grid.DataSource = ds_dk;
            grid.DataBind();
            Response.ClearContent();
            Response.Buffer = true;
            Response.AddHeader("content-disposition", "attachment; filename=DS_Dat_SV5T_CapKhoa.xls");
            Response.ContentType = "application/ms-excel";
            Response.Charset = "UTF-8";
            Response.ContentEncoding = System.Text.Encoding.Unicode;
            Response.BinaryWrite(System.Text.Encoding.Unicode.GetPreamble());
            System.IO.StringWriter sw = new System.IO.StringWriter();
            HtmlTextWriter htw = new HtmlTextWriter(sw);
            htw.Write("<table><tr><td colspan='3'>Danh Sách Đạt SV5T Cấp Khoa</td></tr>");
            grid.RenderControl(htw);
            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();
        }
    }
}

Edu_Hutech/Controllers/SV5T_Khoa_PhongController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Edu_Hutech.Models;
namespace Edu_Hutech.Controllers
{
    public class SV5T_Khoa_PhongController : Controller
    {
        // GET: SV5T_Khoa_Phong
        HutechEduDataContext db = new HutechEduDataContext();
        static string makhoa;

        public ActionResult TrangChu()
        {
            if (Session["Khoa"] == null)
            {
                return RedirectToAction("UserLogin", "UserLogin");
            }
            makhoa = System.Web.HttpContext.Current.Session["Khoa"].ToString();
            ThongKe_DK thongKe = new ThongKe_DK();
            thongKe.Sl_detai_nckh = long.Parse(db.SL_DK_NCKH_TheoKhoa(makhoa).First().tong.ToString());
            thongKe.Sl_dk_lhtt = long.Parse(db.SL_DK_LHTT_TheoKhoa(makhoa).First().tong.ToString());
            thongKe.Sl_sv5t_khoa = long.Parse(db.SoLuong_DK_SV5T_TheoKhoa("K", makhoa).First().Tong.ToString());
            thongKe.Sl_sv5t_truong = long.Parse(db.SoLuong_DK_SV5T_TheoKhoa("TR", makhoa).First().Tong.ToString());
            thongKe.Sl_sv5t_thanh_tw = long.Parse(db.SoLuong_DK_SV5T_TheoKhoa("TH", makhoa).First().Tong.ToString()) +long.Parse(db.SoLuong_DK_SV5T_TheoKhoa("TW", makhoa).First().Tong.ToString());
            thongKe.Tong_dk_sv5t = thongKe.Sl_sv5t_khoa + thongKe.Sl_sv5t_truong + thongKe.Sl_sv5t_thanh_tw;
            return View(thongKe);
        }
        public ActionResult DanhsachDK()
        {
            var lop = db.DSach_DK_SV5T_TheoKhoa(makhoa);
            return View(lop);
        }
        [HttpPost]
        public ActionResult ds_sv_dk(string ma_lop,string ma_cap)
        {
            System.Web.HttpContext.Current.Session["MaCap"] = ma_cap;
            var ds = db.DsachDK_SV5T_Lop(ma_lop, ma_cap).ToList();
                return PartialView(ds);
        }
        public ActionResult danhgia_chitiet_sv(long maPDK, string macap)
        {
            string tai_khoan = System.Web.HttpContext.Current.Session["TaiKhoan_Khoa"].ToString();
            var list_tc = db.GetTaiLieu_SV5T_TheoCap(macap).ToList();
            // luu tiêu chí vào bảng dánh giá của admin với tình trạng là fasle
            var kt_maPDK_2 = db.KQ_DanhGiaND_SV5T_Admins.Where(s => s.MaPDK_SV5T == maPDK).Select(s => s.Dat).FirstOrDefault();
            if ( kt_maPDK_2 == null)
                {
                    foreach (var item in list_tc)
                    {
                        db.Add_KQ_DanhGia_Sv5t_admin(tai_khoan, item.Ma_NDTieuChi, maPDK);
                    }
            }            
            //lay danh sach tieu chi theo maPDK( ten, ma, tinh trang minh chung, đạt hay chưa??)
            var ds = db.DSach_TC_Theo_MaPDK(maPDK).ToList();
            
            System.Web.HttpContext.Current.Session["maPDK"] = maPDK; // lưu lại để chỉnh sửa trạng thái ở KQ_DanhGiaND_SV5T_Admin
            return View(ds);
        }
        public JsonResult tieuchi_dat(string maND, string ghichu)
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Session["maPDK"].ToString());
            if( maND != null)
            {
                db.Danh_Gia_TieuChi_Dat(maPDK, maND);
                db.GhiChu_MinhChung(ghichu, maPDK, maND);
                
                return Json(new { success = true, mess = "Đánh giá thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult tieuchi_chuadat(string maND, string ghichu)
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Session["maPDK"].ToString());
            if (maND != null)
            {
                db.Danh_Gia_TieuChi_ChuaDat(maPDK, maND);
                db.GhiChu_MinhChung(ghichu, maPDK, maND);

                return Json(new { success = true, mess = "Đánh giá thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);

        }

        public ActionResult DanhsachNCKH()
        {
            makhoa = System.Web.HttpContext.Current.Session["Khoa"].ToString();
            var ds_data = db.DS_DeTai_NCKH_theoKhoa(makhoa).ToList();
            List<DanhsachNCKH_Khoa> ds = new List<DanhsachNCKH_Khoa>();

            foreach (var item in ds_data)
            {
                DanhsachNCKH_Khoa ctds = new DanhsachNCKH_Khoa();
                string Ten_GV1 = db.CanBo_HuongDans.Where(s => s.MaGV == item.Ma_GVHD1).Select(s => s.TenGV).FirstOrDefault();
                string Ten_GV2 = db.CanBo_HuongDans.Where(s => s.MaGV == item.Ma_GVHD2).Select(s => s.TenGV).FirstOrDefault();

                ctds.MaPDK_NCKH = item.MaPDK_NCKH;
                ctds.MSSV = item.MSSV;
                ctds.NgayDK = item.NgayDK;
                ctds.TenDeTai = item.TenDeTai;
                ctds.TinhTrang = item.TinhTrang;
                ctds.ten_gv1 = Ten_GV1;
                ctds.ten_gv2 = Ten_GV2;

                ds.Add(ctds);
            }

            return View(ds);
        }

        public ActionResult XetDuyet(long maPDK)
        {
            ChiTietPDK_NCKH ct = new ChiTietPDK_NCKH();
            var chitiet = db.DS_SV_NCKH_theoMaPDK(maPDK).ToList();

            ct.MaPDK_NCKH = chitiet[0].MaPDK_NCKH;
            ct.ND_DeTai = "noidung_NCKH" + "_" + maPDK + ".doc";
            ct.SP_DeTai = "sanpham_NCKH" + "_" + maPDK + ".doc";
            ct.NgayDK = chitiet[0].NgayDK;
            ct.TenDeTai = chitiet[0].TenDeTai;
            ct.TinhTrang = chitiet[0].TinhTrang;

            ct.tenGV_1 = db.CanBo_HuongDans.Where(a => a.MaGV == chitiet[0].Ma_GVHD1).Select(a => a.TenGV).FirstOrDefault();

            ct.tenGV_2 = db.CanBo_HuongDans.Where(a => a.MaGV == chitiet[0].Ma_GVHD2).Select(a => a.TenGV).FirstOrDefault();

            ct.mssv_sv1 = chitiet[0].MSSV;
            ct.hoten_sv1 = chitiet[0].Ho + " " + chitiet[0].Ten;
            ct.malop_sv1 = chitiet[0].MaLop;
            ct.tenkhoa = chitiet[0].TenKhoa;

            if (chitiet.Count > 1)
            {
                ct.sv2 = true;
                ct.hoten_sv2 = chitiet[1].Ho + " " + chitiet[1].Ten;
                ct.mssv_sv2 = chitiet[1].MSSV;
                ct.malop_sv2 = chitiet[1].MaLop;
            }
            if (chitiet.Count > 2)
            {
                ct.sv3 = true;
                ct.hoten_sv3 = chitiet[2].Ho + " " + chitiet[2].Ten;
                ct.mssv_sv3 = chitiet[2].MSSV;
                ct.malop_sv3 = chitiet[2].MaLop;
            }
            if (chitiet.Count > 3)
            {
                ct.sv4 = true;
                ct.hoten_sv4 = chitiet[3].Ho + " " + chitiet[3].Ten;
                ct.mssv_sv4 = chitiet[3].MSSV;
                ct.malop_sv4 = chitiet[3].MaLop;
            }
            if (chitiet.Count > 4)
            {
                ct.sv5 = true;
                ct.hoten_sv5 = chitiet[4].Ho + " " + chitiet[4].Ten;
                ct.mssv_sv5 = chitiet[4].MSSV;
                ct.malop_sv5 = chitiet[4].MaLop;
            }

            return View(ct);
        }

        public ActionResult DuyetPDK()
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Request.Params["maPDK"].ToString());
            if (maPDK != 0)
            {
                db.PDK_NCKH_Khoa_duyet(maPDK);
                return Json(new { success = true, mess = "Đã duyệt thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult HuyPDK()
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Request.Params["maPDK"]);
            if (maPDK != 0)
            {
                db.PDK_NCKH_GV_huy(maPDK);
                return Json(new { success = true, mess = "Đã hủy thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DelPDK()
        {   
            long maPDK = long.Parse(System.Web.HttpContext.Current.Request.Params["maPDK"]);
            if (maPDK != 0)
            {
                db.Del_PDK_NCKH_theoMaPDK(maPDK);
                return Json(new { success = true, mess = "Đã thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult LHTT_ThongKe()
        {

            //string mssv = System.Web.HttpContext.Current.Session["SinhVien"].ToString();
            var a = db.DSach_DK_LHTT();
            return View(a);
        }

        public ActionResult LHTT_Admin_DanhGia(long maPDK)
        {
            string tai_khoan = System.Web.HttpContext.Current.Session["TaiKhoan_Khoa"].ToString();
            var a = db.GetTieuChiLHTT_TheoPDK(maPDK).ToList();
            // luu tiêu chí vào bảng dánh giá của admin với tình trạng là fasle
            var kt_maPDK_2 = db.KQ_DanhGiaND_LHTT_Admins.Where(s => s.MaPDK_LHTT == maPDK).Select(s => s.Diem).FirstOrDefault();
            if (kt_maPDK_2 == null)
            {
                foreach (var item in a)
                {
                    db.Add_KQ_DanhGia_LHTT_admin(tai_khoan, item.Ma_NDTieuChi, maPDK);
                }
            }
            //lay danh sach tieu chi theo maPDK( ten, ma, tinh trang minh chung, đạt hay chưa??)
            var ds = db.DSach_TC_Theo_MaPDK_LHTT(maPDK).ToList();
            System.Web.HttpContext.Current.Session["maPDK"] = maPDK; // lưu lại để chỉnh sửa trạng thái ở KQ_DanhGiaND_SV5T_Admin
            return View(ds);
        }
        public ActionResult tieuchi_dat_LHTT()
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Session["maPDK"].ToString());

Edu_Hutech/Controllers/TimKiemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Edu_Hutech.Models;

namespace Edu_Hutech.Controllers
{
    public class TimKiemController : Controller
    {
        HutechEduDataContext data = new HutechEduDataContext();
        // GET: TimKiem
        [HttpPost]
        public ActionResult KetQuaTimKiem(FormCollection f)
        {
            string sTuKhoa = f["txtTimKiem"].ToString();
            string mssv = data.SinhViens.Where(s => s.MaLop == sTuKhoa && (s.loptruong == true) ).Select(s => s.MSSV).FirstOrDefault();
            var a = data.DSach_DK_LHTT().Where(n => n.MSSV == mssv).ToList();
            return View(a);
        }
       
    }
}

Edu_Hutech/Views/SV5T_Khoa_Phong/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<h2>Mời bạn nhập Mã số sinh viên của bạn lớp trưởng lớp đăng ký :</h2>

    <td>Nhập Mã số sinh viên:</td>
    <td><input id="mssv"/></td>
    <td><button onclick="Submit()">Lưu</button></td>


<script>
    function Submit() {
        var mssv = $('#mssv').val();
        $.ajax({
            type: "POST",
            url: '/SV5T_Khoa_Phong/Create',
            data: {
                mssv: mssv
            },
            dataType: 'json',
            success: function (response) {
                if (response.success) {
                    alert(response.mess);
                    window.location = "/SV5T_Khoa_Phong/LHTT_ThongKe";
                }
                else {
                    alert(response.mess);
                }
            },
            error: function (error) {
                alert("Lỗi!!!" + error);
            }
        })
    }
</script>

Edu_Hutech/Views/SV5T_Khoa_Phong/DanhsachDK.cshtml
@{
    ViewBag.Title = "DanhsachDK";
    Layout = "~/Views/Shared/_LayoutKhoa.cshtml";
}

@model IEnumerable<Edu_Hutech.Models.DSach_DK_SV5T_TheoKhoaResult>
<br />
<p></p>
<div class="input-group">
    <select id="lop">
        @foreach (var item in Model)
        {
            <option value="@item.MaLop">@item.MaLop</option>
        }
    </select>
    <select id="macap">
        <option value="K">Khoa</option>
        <option value="TR">Trường</option>
        <option value="TH">Thành</option>
        <option value="TW">Trung Ương</option>
    </select>
    <a href="#" onclick="load_ds()"><i class="fa fa-refresh fa-spin" style="font-size:20px" ></i></a>
</div>
<table>
    <tr>
        <th>Họ Tên</th>
        <th>Mã Số Sinh Viên</th>
        <th>Tình Trang</th>
    </tr>
    <tr id="ds_dk_sv5t"> </tr>
</table>

<p id="thong_bao"></p>
<script>
    function load_ds() {
        var malop = $('#lop').val();
        var macap = $('#macap').val();
        $.ajax({
            type: "post",
            url: '@Url.Action("ds_sv_dk", "SV5T_Khoa_Phong")',
            data: {
                ma_lop: malop,
                ma_cap: macap
            },
            success: function (a) {
                if (a.success == true) {
                    alert("Không có sinh viên nào được chọn!!!");
                }
                else
                    $('#ds_dk_sv5t').html(a);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(errorThrown)
            },
        });
    }
    window.onload = load_ds;
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

Edu_Hutech/Views/SV5T_Khoa_Phong/DanhsachNCKH.cshtml
@model IEnumerable<Edu_Hutech.Models.DanhsachNCKH_Khoa>

@{
    ViewBag.Title = "DanhsachNCKH";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<link href="~/Content/css/admin/trangchu.css" rel="stylesheet" />

<table>
    <tr>
        <th>
            Tên đề tài
        </th>
        <th>
            Mã số sinh viên đăng ký
        </th>
        <th>
            Ngày đăng ký
        </th>
        <th>
            Tình trạng
        </th>
        <th>
            Giáo viên hướng dẫn 1:
        </th>
        <th>
            Giáo viên hướng dẫn 2:
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenDeTai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MSSV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDK)
            </td>
            @if (item.TinhTrang == 1)
            {
                <td>
                    <p style="color:yellow">Chờ xét duyệt</p>
                </td>
            }
            else if (item.TinhTrang == 2)
            {
                <td>
                    <p style="color:green">Đang thực hiện</p>
                </td>
            }
            else if (item.TinhTrang == 3)
            {
                <td>
                    <p style="color:blue">Đã hoàn thành</p>
                </td>
            }
            else
            {
                <td>
                    <p style="color:gray">Không xác định</p>
                </td>
            }
            <td id="ten_gv1">
                    @Html.DisplayFor(modelItem => item.ten_gv1)
            </td>
            @if (item.Ma_GVHD2 == null)
            {
                <td>
                    Không có
                </td>
            }
            else
            {
                <td id="ten_gv2">
                    @Html.DisplayFor(modelItem => item.ten_gv2)
                </td>
            }
            <td><a id="danhgia" href="@Url.Action("XetDuyet","SV5T_Khoa_Phong",new { maPDK = item.MaPDK_NCKH })" style="color:skyblue">Chi tiết</a></td>
        </tr>
    }

</table>

<p>
    <a href="/SV5T_Khoa_Phong/TrangChu">Trở về</a>
</p>

Edu_Hutech/Views/SV5T_Khoa_Phong/LHTT_ThongKe.cshtml
@model IEnumerable<Edu_Hutech.Models.DSach_DK_LHTTResult>

@{
    ViewBag.Title = "LHTT_ThongKe";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<li><a style="font-size:20px" href="#" id="dangky_LHTT" onclick="them_lhtt()"><i class="fas fa-user-graduate"></i> Đăng Ký </a></li>
<div id="txtTimKiem">
    @using (Html.BeginForm("KetQuaTimKiem", "TimKiem", FormMethod.Post))
    {
        @Html.TextBox("txtTimKiem", "", htmlAttributes: new { @style = "margin-top:10px;border-radius:5px", @class = "TextBoxTimKiem", @placeholder = "nhập lớp cần tìm" })
        <button type="submit">Tìm</button>
    }
</div>
<table class="table">
    <tr>
        <th>
            Số phiếu đăng ký
        </th>
        <th>
            Mã số sinh viên
        </th>
        <th>
            Họ và tên
        </th>
        <th>
            Năm học
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaPDK_LHTT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MSSV)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ho)  @Html.DisplayFor(modelItem => item.Ten)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.NamHoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                <button>
                    <a onclick="truyen_mssv(@item.MSSV)" href="@Url.Action("LHTT_Admin_DanhGia", "SV5T_Khoa_Phong", new { maPDK = item.MaPDK_LHTT })"> 
                        Chi Tiết
                    </a>
                </button>
                |
                <button>
                    <a onclick="DeleteConfirm(@item.MaPDK_LHTT)">
                        Xóa
                    </a>
                </button>
</td>
        </tr>
    }
</table>
<script>
    function them_lhtt() {
        if (window.confirm("Bạn có muốn thêm lớp học tiên tiến không?") == true) {
            window.location.href = '@Url.Action("Create", "SV5T_Khoa_Phong")';
        }
    }
</script>
<script>
    function DeleteConfirm(maPDK) {
        var x = window.confirm("Đồng ý xóa ? ");
        if (x == true) {
            var from_data = new FormData();
            from_data.append("maPDK", maPDK);
            $.ajax({
                type: "POST",
                url: '/SV5T_Khoa_Phong/Delete',
                data: from_data,
                dataType: 'json',
                contentType: false,
                processData: false,
                success: function (response) {
                    if (response.success) {
                        alert(response.mess);
                        location.reload();
                    }
                    else {
                        alert(response.mess);
                    }
                },
                error: function (error) {
                    alert("Lỗi!!!" + error);
                }
            })
        }
        else {
            alert("");
        }
    }
</script>
<script>
    //dung de load minh chung cho sv duoc chon
    function truyen_mssv(mssv) {
        localStorage.setItem("MSSV", mssv);
    }
</script>

Edu_Hutech/Views/SV5T_Khoa_Phong/TrangChu.cshtml
@{
    ViewBag.Title = "TrangChu";
    Layout = "~/Views/Shared/_LayoutKhoa.cshtml";
}
@model Edu_Hutech.Models.ThongKe_DK
<link href="~/Content/css/admin/trangchu.css" rel="stylesheet" />
<h2>Số Lượng sinh viên đăng ký phong trào</h2>
<table>
    <tr>
        <th>Phong Trào</th>
        <th>Cấp Khoa</th>
        <th>Cấp Trường</th>
        <th>Cấp Thành/ Trung Ương</th>
        <th>Tổng Cộng</th>
        <th></th>
    </tr>
    <tr>
        <td>Sinh Viên 5 Tốt</td>
        <td>@Model.Sl_sv5t_khoa</td>
        <td>@Model.Sl_sv5t_truong</td>
        <td>@Model.Sl_sv5t_thanh_tw</td>
        <td>@Model.Tong_dk_sv5t</td>
        <td>
            <div>
                <input type="button" class="btn btn-outline-danger" onclick="location.href='@Url.Action("DanhsachDK", "SV5T_Khoa_Phong" )'" value="Đánh Giá" />

                <div class="btn-group dropright">
                    <button type="button" class="btn btn-outline-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Xuất Danh Sách
                    </button>
                    <div class="dropdown-menu">
                        <!-- Dropdown menu links -->
                        <a class="dropdown-item" style="color:white" href="@Url.Action("Dat_SV5T_Khoa","Report")">Danh sách đạt cấp khoa</a>
                        <a class="dropdown-item" style="color:white" href="#">Danh sách đăng ký cấp trường/ thành</a>
                    </div>
                </div>
            </div>
        </td>
    </tr>
    <tr>
        <td>Nghiên Cứu Khoa Học</td>
        <td></td>
        <td></td>
        <td></td>
        <td>@Model.Sl_detai_nckh</td>
        <td>
            <input type="button" class="btn btn-outline-danger" onclick="location.href='@Url.Action("DanhsachNCKH", "SV5T_Khoa_Phong" )'" value="Quản lý" />
            <button href="#" class="btn btn-outline-danger">Xuất Danh Sách</button>
        </td>
    </tr>

    <tr>
        <td>Lớp Học Tiên Tiến</td>
        <td></td>
        <td></td>
        <td></td>
        <td>@Model.Sl_dk_lhtt</td>
        <td>
            <input type="button" class="btn btn-outline-danger" onclick="location.href='@Url.Action("LHTT_ThongKe", "SV5T_Khoa_Phong" )'" value="Đánh giá" />
            <button href="#" class="btn btn-outline-danger">Xuất Danh Sách</button></td>
    </tr>
</table>

<h2 style="color:initial">Các chức năng khác:</h2>
<a href="/SV5T_Khoa_Phong/Loptruong">Quản lý lớp trưởng các lớp</a>

Edu_Hutech/Views/SV5T_Khoa_Phong/ds_sv_dk.cshtml
@model IEnumerable<Edu_Hutech.Models.DsachDK_SV5T_LopResult>

@foreach (var item in Model)
{
<tr>
    <td>@item.Ho @item.Ten</td>
    <td>@item.MSSV</td>
    <td><a id="danhgia" onclick="truyen_mssv(@item.MSSV)" href="@Url.Action("danhgia_chitiet_sv","SV5T_Khoa_Phong",new { maPDK = item.MaPDK_SV5T, macap = item.MaCap })" target="_blank" style="color:red">Đánh Giá</a></td>
</tr>
}

<script>
    localStorage.clear();
</script>
<script>
    //dung de load minh chung cho sv duoc chon
    function truyen_mssv(mssv) {
        localStorage.setItem("MSSV", mssv);
    }
</script>