Edu_Hutech/Controllers/NCKH_GVController.cs
using Edu_Hutech.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Edu_Hutech.Controllers
{
    public class NCKH_GVController : Controller
    {
        HutechEduDataContext db = new HutechEduDataContext();

        // GET: NCKH_GV
        public ActionResult Index()
        {
            string maGV = System.Web.HttpContext.Current.Session["TaiKhoan_GV"].ToString();
            var ds_PDK = db.DS_DeTai_NCKH_theoGV(maGV).ToList();
            return View(ds_PDK);
        }

        public ActionResult KiemDuyet(long maPDK)
        {
            ChiTietPDK_NCKH ct = new ChiTietPDK_NCKH();
            var chitiet = db.DS_SV_NCKH_theoMaPDK(maPDK).ToList();

            ct.MaPDK_NCKH = chitiet[0].MaPDK_NCKH;
            ct.ND_DeTai = "noidung_NCKH" + "_" + maPDK + ".doc";
            ct.SP_DeTai = "sanpham_NCKH" + "_" + maPDK + ".doc";
            ct.NgayDK = chitiet[0].NgayDK;
            ct.TenDeTai = chitiet[0].TenDeTai;
            ct.TinhTrang = chitiet[0].TinhTrang;

            ct.tenGV_1 = db.CanBo_HuongDans.Where(a => a.MaGV == chitiet[0].Ma_GVHD1).Select(a => a.TenGV).FirstOrDefault();

            ct.tenGV_2 = db.CanBo_HuongDans.Where(a => a.MaGV == chitiet[0].Ma_GVHD2).Select(a => a.TenGV).FirstOrDefault();

            ct.mssv_sv1 = chitiet[0].MSSV;
            ct.hoten_sv1 = chitiet[0].Ho + " " + chitiet[0].Ten;
            ct.malop_sv1 = chitiet[0].MaLop;
            ct.tenkhoa = chitiet[0].TenKhoa;

            if (chitiet.Count > 1)
            {
                ct.sv2 = true;
                ct.hoten_sv2 = chitiet[1].Ho + " " + chitiet[1].Ten;
                ct.mssv_sv2 = chitiet[1].MSSV;
                ct.malop_sv2 = chitiet[1].MaLop;
            }
            if (chitiet.Count > 2)
            {
                ct.sv3 = true;
                ct.hoten_sv3 = chitiet[2].Ho + " " + chitiet[2].Ten;
                ct.mssv_sv3 = chitiet[2].MSSV;
                ct.malop_sv3 = chitiet[2].MaLop;
            }
            if (chitiet.Count > 3)
            {
                ct.sv4 = true;
                ct.hoten_sv4 = chitiet[3].Ho + " " + chitiet[3].Ten;
                ct.mssv_sv4 = chitiet[3].MSSV;
                ct.malop_sv4 = chitiet[3].MaLop;
            }
            if (chitiet.Count > 4)
            {
                ct.sv5 = true;
                ct.hoten_sv5 = chitiet[4].Ho + " " + chitiet[4].Ten;
                ct.mssv_sv5 = chitiet[4].MSSV;
                ct.malop_sv5 = chitiet[4].MaLop;
            }

            return View(ct);
        }

        public ActionResult Luu()
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Request.Params["maPDK"].ToString());
            string ten_dt = System.Web.HttpContext.Current.Request.Params["ten_dt"];

            var file_nd = Request.Files["file_nd"];

            var file_sp = Request.Files["file_sp"];

            string mssv = db.PhieuDangKy_DeTai_NCKHs.Where(s => s.MaPDK_NCKH == maPDK).Select(s => s.ND_DeTai).FirstOrDefault();
            string url = db.MinhChungs.Where(s => s.TenMInhChung == mssv).Select(s => s.URL).First().ToString();

            if (ten_dt == "")
            {
                return Json(new { success = false, mess = "Đề nghị nhập tên đề tài" }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                if (file_nd == null || file_sp == null)
                {
                    db.PDK_NCKH_GV_Sua(maPDK, ten_dt);
                    return Json(new { success = true, mess = "Đã cập nhật thành công!" }, JsonRequestBehavior.AllowGet);
                }
                else if (file_nd.FileName == "" || file_sp.FileName == "")
                {
                    ViewBag.Thongbao = "Bổ sung tệp để hoàn thành đăng ký";
                }
                else
                {
                    db.PDK_NCKH_GV_Sua(maPDK, ten_dt);

                    var nd = Path.Combine(Server.MapPath(url), "noidung_NCKH" + "_" + maPDK + ".doc");
                    file_nd.SaveAs(nd);
                    var sp = Path.Combine(Server.MapPath(url), "sanpham_NCKH" + "_" + maPDK + ".doc");
                    file_sp.SaveAs(sp);

                    return Json(new { success = true, mess = "Đã cập nhật thành công!" }, JsonRequestBehavior.AllowGet);
                }
                return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Download(long? maPDK, string ten)
        {
            string mssv = db.PhieuDangKy_DeTai_NCKHs.Where(s => s.MaPDK_NCKH == maPDK).Select(s => s.ND_DeTai).FirstOrDefault();
            string url = db.MinhChungs.Where(s => s.TenMInhChung == mssv).Select(s => s.URL).First().ToString();
            var FileVirtualPath = url + "/" + ten + "_" + maPDK + ".doc";
            return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        }

        public ActionResult ChinhSua()
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Request.Params["maPDK"].ToString());
            if (maPDK != 0)
            {

                return Json(new { success = true, mess = "Đã duyệt thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DuyetPDK()
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Request.Params["maPDK"].ToString());
            if (maPDK != 0)
            {
                db.PDK_NCKH_GV_duyet(maPDK);
                return Json(new { success = true, mess = "Đã duyệt thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult HuyPDK()
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Request.Params["maPDK"]);
            if (maPDK != 0)
            {
                db.PDK_NCKH_GV_huy(maPDK);
                return Json(new { success = true, mess = "Đã hủy thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult DelPDK()
        {
            long maPDK = long.Parse(System.Web.HttpContext.Current.Request.Params["maPDK"]);
            if (maPDK != 0)
            {
                db.Del_PDK_NCKH_theoMaPDK(maPDK);
                return Json(new { success = true, mess = "Đã thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Có Lỗi" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Edu_Hutech/Views/NCKH_GV/Index.cshtml
@model IEnumerable<Edu_Hutech.Models.DS_DeTai_NCKH_theoGVResult>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<link href="~/Content/css/admin/trangchu.css" rel="stylesheet" />
<h2>Index</h2>

<table>
    <tr>
        <th>
            Tên đề tài
        </th>
        <th>
            Mã số sinh viên đăng ký
        </th>
        <th>
            Ngày đăng ký
        </th>
        <th>
            Tình trạng
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TenDeTai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ND_DeTai)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NgayDK)
            </td>
            @if (item.TinhTrang == -1)
            {
                <td>
                    <p style="color:yellow">Chờ xét duyệt</p>
                </td>
            }
            else if (item.TinhTrang == 0)
            {
                <td>
                    <p style="color:red">Đã hủy</p>
                </td>
            }
            else if (item.TinhTrang == 1)
            {
                <td>
                    <p style="color:deepskyblue">Đã duyệt</p>
                </td>
            }
            else if (item.TinhTrang == 2)
            {
                <td>
                    <p style="color:green">Đang thực hiện</p>
                </td>
            }
            else if (item.TinhTrang == 3)
            {
                <td>
                    <p style="color:blue">Đã hoàn thành</p>
                </td>
            }
            else
            {
                <td>
                    <p style="color:gray">Không xác định</p>
                </td>
            }
            <td><a id="danhgia" href="@Url.Action("KiemDuyet","NCKH_GV",new { maPDK = item.MaPDK_NCKH })" style="color:skyblue">Chi tiết</a></td>
        </tr>
    }

</table>

Edu_Hutech/Views/NCKH_GV/KiemDuyet.cshtml
@model Edu_Hutech.Models.ChiTietPDK_NCKH

@{
    ViewBag.Title = "KiemDuyet";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<br />
<h2>CHI TIẾT ĐỀ TÀI NGHIÊN CỨU KHOA HỌC</h2>
<h3 style="color:red">@ViewBag.Thongbao</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Giáo viên hướng dẫn:
        </dt>

        <dd style="padding-left: 100px">
            @Html.DisplayFor(model => model.tenGV_1)
        </dd>

        @if (Model.tenGV_2 != null)
        {
            <dt>
                Giáo viên hướng dẫn:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.tenGV_2)
            </dd>
        }

        <dt>
            Tên Đề tài:
        </dt>

        <dd style="padding-left: 100px">
            <input name="ten_detai" placeholder="Tên Đề Tài" type="text" id="ten_detai" value="@Html.DisplayFor(model => model.TenDeTai)" disabled />
        </dd>

        <dt>
            Nội dung thực hiện:
        </dt>

        <dd style="padding-left: 100px">
            <p id="file_nd">@Model.ND_DeTai</p>
            <input onclick="upload('#file_noidung','#file_nd')" type="file" accept="application/msword" name="file_noidung" id="file_noidung" style="display:none" />
            <p id="download_nd_NCKH">@Html.ActionLink("Download", "Download", new { maPDK = @Model.MaPDK_NCKH, ten = "noidung_NCKH" })</p>
        </dd>

        <dt>
            Sản phẩm dự kiến thực hiện:
        </dt>

        <dd style="padding-left: 100px">
            <p id="file_sp">@Model.SP_DeTai</p>
            <input onclick="upload('#file_sp_dukien','#file_sp')" type="file" accept="application/msword" name="file_sp_dukien" id="file_sp_dukien" style="display:none" />
            <p id="download_sp_NCKH">@Html.ActionLink("Download", "Download", new { maPDK = @Model.MaPDK_NCKH, ten = "sanpham_NCKH" })</p>
        </dd>

        <dt>
            Ngày đăng ký:
        </dt>

        <dd style="padding-left: 100px">
            @Html.DisplayFor(model => model.NgayDK)
        </dd>

        <dt>
            Tình trạng:
        </dt>

        @if (Model.TinhTrang == -1)
        {
            <dd style="padding-left: 100px">
                <p style="color:yellow">Chờ xét duyệt</p>
            </dd>
        }
        else if (Model.TinhTrang == 0)
        {
            <dd style="padding-left: 100px">
                <p style="color:red">Đã hủy</p>
            </dd>
        }
        else if (Model.TinhTrang == 1)
        {
            <dd style="padding-left: 100px">
                <p style="color:deepskyblue">Đã duyệt</p>
            </dd>
        }
        else if (Model.TinhTrang == 2)
        {
            <dd style="padding-left: 100px">
                <p style="color:green">Đang thực hiện</p>
            </dd>
        }
        else if (Model.TinhTrang == 3)
        {
            <dd style="padding-left: 100px">
                <p style="color:blue">Đã hoàn thành</p>
            </dd>
        }
        else
        {
            <dd style="padding-left: 100px">
                <p style="color:gray">Không xác định</p>
            </dd>
        }

        <dt>
            Mã số sinh viên 1:
        </dt>

        <dd style="padding-left: 100px">
            @Html.DisplayFor(model => model.mssv_sv1)
        </dd>

        <dt>
            Họ và tên sinh viên 1:
        </dt>

        <dd style="padding-left: 100px">
            @Html.DisplayFor(model => model.hoten_sv1)
        </dd>

        <dt>
            Lớp:
        </dt>

        <dd style="padding-left: 100px">
            @Html.DisplayFor(model => model.malop_sv1)
        </dd>

        <dt>
            Khoa:
        </dt>

        <dd style="padding-left: 100px">
            @Html.DisplayFor(model => model.tenkhoa)
        </dd>
        @if (Model.sv2 == true)
        {
            <dt>
                Mã số sinh viên 2:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.mssv_sv2)
            </dd>

            <dt>
                Họ và tên sinh viên 2:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.hoten_sv2)
            </dd>

            <dt>
                Lớp:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.malop_sv2)
            </dd>
        }
        @if (Model.sv3 == true)
        {
            <dt>
                Mã số sinh viên 3:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.mssv_sv3)
            </dd>

            <dt>
                Họ và tên sinh viên 3:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.hoten_sv3)
            </dd>

            <dt>
                Lớp:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.malop_sv3)
            </dd>
        }
        @if (Model.sv4 == true)
        {
            <dt>
                Mã số sinh viên 4:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.mssv_sv4)
            </dd>

            <dt>
                Họ và tên sinh viên 4:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.hoten_sv4)
            </dd>

            <dt>
                Lớp:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.malop_sv4)
            </dd>
        }
        @if (Model.sv5 == true)
        {
            <dt>
                Mã số sinh viên 5:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.mssv_sv5)
            </dd>

            <dt>
                Họ và tên sinh viên 5:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.hoten_sv5)
            </dd>

            <dt>
                Lớp:
            </dt>

            <dd style="padding-left: 100px">
                @Html.DisplayFor(model => model.malop_sv5)
            </dd>
        }
    </dl>
</div>

<table>
    @if (Model.TinhTrang == -1)
    {
        <td id="Change">
            <button onclick="Change()" href="#" style="color:skyblue">Chỉnh sửa</button>
        </td>
        <td id="Luu" style="display:none">
            <button onclick="Luu('@Model.MaPDK_NCKH')" href="#" style="color:skyblue">Lưu</button>
        </td>
        <td id="Huy" style="display:none">
            <button onclick="LoaiBo()" href="#" style="color:black">Hủy</button>
        </td>
        <td>
            <button onclick="Duyet('@Model.MaPDK_NCKH')" href="#" style="color:green">Duyệt</button>
        </td>
        <td>
            <button onclick="Huy('@Model.MaPDK_NCKH')" href="#" style="color:red">Loại bỏ</button>
        </td>
    }
    @if (Model.TinhTrang == 1)
    {
        <td>
            <button onclick="Huy('@Model.MaPDK_NCKH')" href="#" style="color:red">Loại bỏ</button>
        </td>
    }
    <td>
        <button onclick="Del('@Model.MaPDK_NCKH')" href="#" style="color:red">Xóa khỏi danh sách</button>
    </td>
</table>
<br />
<p>
    @Html.ActionLink("Trở về danh sách", "Index")
</p>

<script>
    function Change() {
        $('#Change').css('display', 'none');
        $('#Luu').css('display', 'block');

        $("#ten_detai").prop("disabled", false);
        $("#ten_detai").css({ 'color': 'black', 'background': 'skyblue' });

        document.getElementById("file_noidung").setAttribute("style", "display: block");
        document.getElementById("download_nd_NCKH").setAttribute("style", "display: none");

        $('#file_nd').css('display', 'none');
        $('#file_sp').css('display', 'none');
        $('#Huy').css('display', 'block');

        document.getElementById("file_sp_dukien").setAttribute("style", "display: block");
        document.getElementById("download_sp_NCKH").setAttribute("style", "display: none");
    };
    function Luu(maPDK) {
        var ten_dt = $('#ten_detai').val();
        var from_data = new FormData();
        var file_nd = $('#file_noidung').get(0).files;
        var file_sp = $('#file_sp_dukien').get(0).files;
        from_data.append("maPDK", maPDK);
        from_data.append("ten_dt", ten_dt);
        from_data.append("file_nd", file_nd[0]);
        from_data.append("file_sp", file_sp[0]);
        $.ajax({
            type: "POST",
            url: '/NCKH_GV/Luu',
            data: from_data,
            dataType: 'json',
            contentType: false,
            processData: false,
            success: function (response) {
                if (response.success) {
                    alert("Đã chỉnh sửa thành công ");
                    location.reload();
                }
                else {
                    alert(response.mess);
                }
            },
            error: function (error) {
                alert("Đề nghị nhập tên đề tài");
            }
        })
    }
</script>

<script>
    function upload(id, name_file) {
        $(id).trigger('click');
        $(id).change(function () {
            var filename = $(id).val().split('\\').pop();
            $(name_file).text(filename);
        });
    }
</script>

<script>
    function LoaiBo() {
        location.reload();
    }
</script>

<script>
    function Duyet(maPDK) {
        var x = window.confirm("Đồng ý đề tài ? ");
        if (x == true) {
            var from_data = new FormData();
            from_data.append("maPDK", maPDK);
            $.ajax({
                type: "POST",
                url: '/NCKH_GV/DuyetPDK',
                data: from_data,
                dataType: 'json',
                contentType: false,
                processData: false,
                success: function (response) {
                    if (response.success) {
                        alert("Cám ơn đã đồng ý ");
                        location.reload();
                    }
                    else {
                        alert(response.mess);
                    }
                },
                error: function (error) {
                    alert("Lỗi!!!" + error);
                }
            })
        }
        else {
            alert("Cần xem xét lại ");
        }
    }
</script>

<script>
    function Huy(maPDK) {
        var x = confirm("Hủy bỏ đề tài ? ");
        if (x == true) {
            var y = prompt("Nhập 'Cancel' để loại bỏ đề tài");
            if (y == "Cancel") {
                var from_data = new FormData();
                from_data.append("maPDK", maPDK);
                $.ajax({
                    type: "POST",
                    url: '/NCKH_GV/HuyPDK',
                    data: from_data,
                    dataType: 'json',
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        if (response.success) {
                            alert("Đã hủy thành công ");
                            location.reload();
                        }
                        else {
                            alert(response.mess);
                        }
                    },
                    error: function (error) {
                        alert("Lỗi!!!" + error);
                    }
                })
            }
            else {
                alert("Đã nhập sai");
            }
        }
        else {
            alert("Cám ơn đã xem xét lại ");
        }
    }
</script>

<script>
    function Del(maPDK) {
        var x = window.confirm("Xóa đề tài khỏi danh sách ? ");
        if (x == true) {
            var y = prompt("Nhập 'Delete' để xóa ");
            if (y == "Delete") {
                var from_data = new FormData();
                from_data.append("maPDK", maPDK);
                $.ajax({
                    type: "POST",
                    url: '/NCKH_GV/DelPDK',
                    data: from_data,
                    dataType: 'json',
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        if (response.success) {
                            alert("Đã xóa thành công ");
                            window.location = "/NCKH_GV/Index";
                        }
                        else {
                            alert(response.mess);
                        }
                    },
                    error: function (error) {
                        alert("Lỗi!!!" + error);
                    }
                })
            }
            else {
                alert("Đã nhập sai");
            }
        }
        else {
            alert("Hãy cẩn thận hơn ");
        }
    }
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>