Edu_Hutech/Controllers/SinhVien5TotController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Edu_Hutech.Models;

namespace Edu_Hutech.Controllers
{
    public class SinhVien5TotController : Controller
    {
        // GET: SinhVien5Tot
        HutechEduDataContext db = new HutechEduDataContext();

        static string mssv;
        
        public ActionResult Index()
        {
            
            if (Session["SinhVien"] == null)
            {
                return RedirectToAction("UserLogin", "UserLogin");
            }
            mssv = System.Web.HttpContext.Current.Session["SinhVien"].ToString();
            var ho = db.SinhViens.Where(s => s.MSSV == mssv).Select(s => s).SingleOrDefault();
            string hoten = ho.Ho + " " + ho.Ten;
            ViewBag.HoTen = hoten;
            return View();
        }
        [HttpGet]
        public ActionResult Thongtin_sinhvien()
        {
            var ttsv = db.SinhViens.Where(s => s.MSSV == mssv).SingleOrDefault();
            return View(ttsv);
        }
        [HttpPost]
        public ActionResult Thongtin_sinhvien(FormCollection formCollection)
        {
            string sdt;
            if(formCollection["sdt"] != null)
            {
                sdt = formCollection["sdt"].ToString();
            }
            else
            {
                sdt = null;
            }
            string quequan;
            if (formCollection["quequan"] != null)
            {
                quequan = formCollection["quequan"].ToString();
            }
            else
            {
                quequan = null;
            }
            string email;
            if (formCollection["email"] != null)
            {
                email = formCollection["email"].ToString();
            }
            else
            {
                email = null;
            }
            string noisinh;
            if (formCollection["noisinh"] != null)
            {
                noisinh = formCollection["noisinh"].ToString();
            }
            else
            {
                noisinh = null;
            }
            string diachi_cutru;
            if (formCollection["diachi_cutru"] != null)
            {
                diachi_cutru = formCollection["diachi_cutru"].ToString();
            }
            else
            {
                diachi_cutru = null;
            }
            string diachi_lienlac;
            if (formCollection["diachi_lienlac"] != null)
            {
                diachi_lienlac = formCollection["diachi_lienlac"].ToString();
            }
            else
            {
                diachi_lienlac = null;
            }
            string ngay_vaodoan;
            if (formCollection["ngay_vaodoan"] != null)
            {
                ngay_vaodoan = formCollection["ngay_vaodoan"].ToString();
            }
            else
            {
                ngay_vaodoan = null;
            }
            string ngay_dang_dubi;
            if (formCollection["ngay_dang_dubi"] != null)
            {
                ngay_dang_dubi = formCollection["ngay_dang_dubi"].ToString();
            }
            else
            {
                ngay_dang_dubi = null;
            }
            string ngay_dang_chinhthuc;
            if (formCollection["ngay_dang_chinhthuc"] != null)
            {
                ngay_dang_chinhthuc = formCollection["ngay_dang_chinhthuc"].ToString();
            }
            else
            {
                ngay_dang_chinhthuc = null;
            }
            string chuc_vu_doan;
            if (formCollection["chuc_vu_doan"] != null)
            {
                chuc_vu_doan = formCollection["chuc_vu_doan"].ToString();
            }
            else
            {
                chuc_vu_doan = null;
            }
            db.Capnhat_TTSV(long.Parse(sdt), quequan, email, noisinh, diachi_cutru, diachi_lienlac, DateTime.Parse(ngay_vaodoan), DateTime.Parse(ngay_dang_dubi), DateTime.Parse(ngay_dang_chinhthuc), chuc_vu_doan, mssv);
            var ttsv = db.SinhViens.Where(s => s.MSSV == mssv).SingleOrDefault();
            return View(ttsv);
        }
        public ActionResult SV5T()
        {
            var ho = db.SinhViens.Where(s => s.MSSV == mssv).Select(s => s).SingleOrDefault();
            string hoten = ho.Ho + " " + ho.Ten;
            ViewBag.HoTen = hoten;
            var PDK = db.PhieuDangKy_SV5Ts.Where(s => s.MSSV == mssv).Select(s => s).FirstOrDefault();
            if (PDK == null)
            {
                return View();
            }
            string macap = PDK.MaCap;
            return RedirectToAction("theodoi_SV5T", new { macap = macap});
        }

        [HttpPost]
        public ActionResult Dky()
        {
            var maMC = db.MinhChungs.Where(a => a.TenMInhChung == mssv).Select(a => a.MaMinhChung).FirstOrDefault();
            string years = DateTime.Now.ToString().Trim();
            int year = Int32.Parse(years.Substring(6, 4));
            string macap = System.Web.HttpContext.Current.Request.Params["dky_sv5t"];            
            var tam = db.GetTaiLieu_SV5T_TheoCap(macap).ToList();
            int? maPDK = db.DKy_SV5T(maMC, macap, year, mssv).First().MaPDK;
            foreach (var item in tam)
                {
                    db.DKy_SV5T_2(maPDK,item.Ma_NDTieuChi);
                }
                db.SubmitChanges();
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult theodoi_SV5T(string macap)
        {
            var ho = db.SinhViens.Where(s => s.MSSV == mssv).Select(s => s).SingleOrDefault();
            string hoten = ho.Ho + " " + ho.Ten;
            ViewBag.HoTen = hoten;
            System.Web.HttpContext.Current.Session["MaCap"] = macap;
            var theo_doi = db.GetTieuChiSV5T_TheoMSSV_TheoCap(mssv,macap).ToList();
            return View(theo_doi);
        }
        public ActionResult LHTT()
        {
            var ho = db.SinhViens.Where(s => s.MSSV == mssv).Select(s => s).SingleOrDefault();
            string hoten = ho.Ho + " " + ho.Ten;
            ViewBag.HoTen = hoten;
            return View();
        }

        public void Report()
        {
            var pdk = db.PhieuDangKy_SV5Ts.Where(s => s.MSSV == mssv).Select(s => s).FirstOrDefault();
            var mc = db.CapDanhHieus.Where(s => s.MaCap == pdk.MaCap).Select(s => s).FirstOrDefault();
            var sv = db.SinhViens.Where(s => s.MSSV == mssv).Select(s => s).SingleOrDefault();
            var lop = db.Lops.Where(s => s.MaLop == sv.MaLop).Select(s => s).SingleOrDefault();
            var khoa = db.Khoas.Where(s => s.MaKhoa == lop.MaKhoa).Select(s => s).SingleOrDefault();
            
            string templatePath = Server.MapPath("~/Template/BieuMauSV5T.doc");
            Microsoft.Office.Interop.Word.Application app = new Microsoft.Office.Interop.Word.Application();
            Microsoft.Office.Interop.Word.Document doc = new Microsoft.Office.Interop.Word.Document();
            doc = app.Documents.Open(templatePath);
            doc.Activate();
            string gioitinh;
            if (sv.GioiTinh != null)
            {
                if (sv.GioiTinh == true)
                {
                    gioitinh = "Nam";
                }
                else { gioitinh = "Nữ"; }
            }
            else { gioitinh = "Không xác định"; }
            if (doc.Bookmarks.Exists("cap"))
            {
                doc.Bookmarks["cap"].Range.Text= mc.TenCap.ToUpper();
            }
            if (doc.Bookmarks.Exists("gioitinh"))
            {
                doc.Bookmarks["gioitinh"].Range.Text = gioitinh;
            }
            if (doc.Bookmarks.Exists("chucvu_Doan"))
            {
                doc.Bookmarks["chucvu_Doan"].Range.Text = sv.ChucVuDoan_neuco;
            }
            if (doc.Bookmarks.Exists("chuyennganh"))
            {
                doc.Bookmarks["chuyennganh"].Range.Text = "";
            }
            if (doc.Bookmarks.Exists("diachicutru"))
            {
                doc.Bookmarks["diachicutru"].Range.Text = sv.DiaChiCuTru;
            }
            if (doc.Bookmarks.Exists("diachilienlac"))
            {
                doc.Bookmarks["diachilienlac"].Range.Text = sv.DiaChiLienLac;
            }
            if (doc.Bookmarks.Exists("dienthoai"))
            {
                doc.Bookmarks["dienthoai"].Range.Text = sv.DiaChiLienLac;
            }
            if (doc.Bookmarks.Exists("email"))
            {
                doc.Bookmarks["email"].Range.Text = sv.Email;
            }
            if (doc.Bookmarks.Exists("hoten"))
            {
                doc.Bookmarks["hoten"].Range.Text = sv.Ho + " " + sv.Ten;
            }
            if (doc.Bookmarks.Exists("lop"))
            {
                doc.Bookmarks["lop"].Range.Text = lop.MaLop.ToString();
            }
            if (doc.Bookmarks.Exists("MSSV"))
            {
                doc.Bookmarks["MSSV"].Range.Text = sv.MSSV;
            }

            DateTime now = DateTime.Now;

            if (doc.Bookmarks.Exists("nam"))
            {
                doc.Bookmarks["nam"].Range.Text = now.Year.ToString();
            }

            int[] namhoc = Namhoc(now);
            if (doc.Bookmarks.Exists("namhoc"))
            {
                doc.Bookmarks["namhoc"].Range.Text = namhoc[0].ToString() + "-" + namhoc[1].ToString();
            }

            int namnhaphoc = int.Parse("20" + sv.MSSV.Substring(0, 2));
            if (doc.Bookmarks.Exists("namthu"))
            {
                doc.Bookmarks["namthu"].Range.Text = (Namhoc(now)[1] - namnhaphoc).ToString();
            }
            if (doc.Bookmarks.Exists("ngay"))
            {
                doc.Bookmarks["ngay"].Range.Text = now.Day.ToString();
            }
            if (doc.Bookmarks.Exists("thang"))
            {

Edu_Hutech/Views/SinhVien5Tot/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>Thông báo</h2>

<h3>@ViewBag.ThongBao</h3>
<hr style="border:dashed" />

Edu_Hutech/Views/SinhVien5Tot/LHTT.cshtml
@{
    ViewBag.Title = "LHTT";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<h2>LHTT</h2>

Edu_Hutech/Views/SinhVien5Tot/Thongtin_sinhvien.cshtml
@model Edu_Hutech.Models.SinhVien

@{
    ViewBag.Title = "Thongtin_sinhvien";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<link href="~/Content/css/about_sv.css" rel="stylesheet" />
<h2>Thông Tin: @Html.DisplayFor(model => model.Ho) @Html.DisplayFor(model => model.Ten)</h2>
@using (Html.BeginForm())
{
<form>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                <label>Họ Tên: </label>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Ho) @Html.DisplayFor(model => model.Ten)
            </dd>
            <dt>
                <label>Lớp: </label>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.MaLop)
            </dd>
            <dt>
                <label>Sinh Nhật:</label>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.NgaySinh)
            </dd>

            <dt>
                <label>Số điện thoại:</label>
            </dt>

            <dd>
                @if (Model.SDT != null)
                {
                    <span>0</span>@Html.DisplayFor(model => model.SDT)
                }
                else
                {
                    <input type="number" name="sdt" placeholder="Nhập sdt của bạn" />
                }
            </dd>

            <dt>
                <label>Quê Quán: </label>
            </dt>

            <dd>

                @if (Model.QueQuan != null)
                {
                    @Html.DisplayFor(model => model.QueQuan)
                }
                else
                {
                    <input type="text" name="quequan" placeholder="Nhập quê quán của bạn" />
                }
            </dd>

            <dt>
                <label>Giới Tính: </label>
            </dt>

            <dd>
                @if (Model.GioiTinh == true)
                {
                    <span>Nam</span>
                }
                else
                {
                    <span>Nữ</span>
                }
            </dd>

            <dt>
                <label>Email: </label>
            </dt>

            <dd>
                @if (Model.Email != null)
                {
                    @Html.DisplayFor(model => model.Email)
                }
                else
                {
                    <input type="email" name="email" placeholder="Nhập email của bạn" />
                }
            </dd>

            <dt>
                <label>Nơi Sinh:</label>
            </dt>

            <dd>
                @if (Model.NoiSinh != null)
                {
                    @Html.DisplayFor(model => model.NoiSinh)
                }
                else
                {
                    <input type="text" name="noisinh" placeholder="Nhập nơi sinh (tỉnh/tp) của bạn" />
                }
            </dd>

            <dt>
                <label>Địa Chỉ Cư Trú: </label>
            </dt>

            <dd>
                @if (Model.DiaChiCuTru != null)
                {
                    @Html.DisplayFor(model => model.DiaChiCuTru)
                }
                else
                {
                    <input type="text" name="diachi_cutru" placeholder="Nhập địa chỉ cư trú của bạn" />
                }
            </dd>

            <dt>
                <label>Địa Chỉ Liên Lạc: </label>
            </dt>

            <dd>
                @if (Model.DiaChiLienLac != null)
                {
                    @Html.DisplayFor(model => model.DiaChiLienLac)
                }
                else
                {
                    <input type="text" name="diachi_lienlac" placeholder="Nhập địa chỉ liên lạc của bạn" />
                }
            </dd>

            <dt>
                <label>Ngày Vào Đoàn (nếu có): </label>
            </dt>
            <dd>
                @if (Model.NgayKetNapDoan != null)
                {
                    @Html.DisplayFor(model => model.NgayKetNapDoan)
                }
                else
                {
                    <input type="date" class="ngay-about-me" name="ngay_vaodoan" placeholder="Nhập địa ngày vào đoàn của bạn" />
                }
            </dd>

            <dt>
                <label>Ngày Vào Đảng Dự Bị ( nếu có): </label>
            </dt>

            <dd>
                @if (Model.NgayVaoDang_dubi_neuco != null)
                {
                    @Html.DisplayFor(model => model.NgayVaoDang_dubi_neuco)
                }
                else
                {
                    <input type="date" class="form-control ngay-about-me" name="ngay_dang_dubi" placeholder="Nhập địa ngày vào đảng dự bị của bạn (nếu có)" />
                }
            </dd>

            <dt>
                <label>Ngày Vào Đảng Chính Thức( nếu có): </label>
            </dt>

            <dd>
                @if (Model.NgayVaoDang_chinhthuc_neuco != null)
                {
                    @Html.DisplayFor(model => model.NgayVaoDang_chinhthuc_neuco)
                }
                else
                {
                    <input type="date" class="form-control ngay-about-me" name="ngay_dang_chinhthuc" placeholder="Nhập địa ngày vào đảng của bạn (nếu có)" />
                }
            </dd>

            <dt>
                <label>Chức Vụ Đoàn (nếu có):</label>
            </dt>

            <dd>
                @if (Model.NgayVaoDang_chinhthuc_neuco != null)
                {
                    @Html.DisplayFor(model => model.ChucVuDoan_neuco)
                }
                else
                {
                    <input type="text" class="form-control ngay-about-me" name="chuc_vu_doan" placeholder="Nhập chức vụ đoàn của bạn (nếu có)" />
                }
            </dd>
        </dl>
    </div>
    <div class="input-group">
        <input type="submit" value="Lưu thông tin" />
    </div>
</form>
}

Edu_Hutech/Views/SinhVien5Tot/theodoi_SV5T.cshtml
@{
    ViewBag.Title = "theodoi_SV5T";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<h2> Tiến độ hoàn thành tiêu chí Sinh Viên 5 Tốt</h2>
@model IEnumerable<Edu_Hutech.Models.GetTieuChiSV5T_TheoMSSV_TheoCapResult>
<input type="file" name="file" accept="image/*" id="file_up" style="display:none" />
<table id="data_sv5t">
    <tr>
        <th>Tiêu Chí</th>
        <th>Minh Chứng</th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            @if (item.Diem != 0)
            {
                <td>
                    @item.TenNDTieuChi  :  @item.Diem
                </td>
                <td></td>
            }
            else
            {
                if (item.TinhTrang == false)
                {
                    <td>
                        @item.TenNDTieuChi
                    </td>
                    <td> <a id="@item.Ma_NDTieuChi" class="up_minhchung button" href="#" onclick="box_upminhchung('@item.Ma_NDTieuChi','@item.MSSV')" style="color:red"> Chưa nộp minh chứng </a></td>
                }
                else
                {
                    <td>
                        @item.TenNDTieuChi
                    </td>
                    <td> <a class="up_minhchung button" href="#" onclick="show_minhchung('@item.Ma_NDTieuChi','@item.MSSV')" style="color:#0058ff"> Đã hoàn thành minh chứng </a></td>
                }
            }
        </tr>
    }
</table>
<br />
<br />
<button onclick="location.href='@Url.Action("Report", "SinhVien5Tot" )'" id="inWord" style="color:#0058ff; float:right">In file word</button> 

<div class="minhchung_box" id="upminhchung">
    <div _ngcontent-c15="" class="modal-content text-center">
        <div _ngcontent-c15="" class="modal-header">
            <h4 _ngcontent-c15="" class="modal-title">Quản lý minh chứng</h4>
            <button _ngcontent-c15="" aria-label="Close" class="close">
                <span _ngcontent-c15="" aria-hidden="true">×</span>
            </button>
        </div>
        <div _ngcontent-c15="" class="modal-body">
            <my-image-upload _ngcontent-c15="" _nghost-c16="" ng-reflect-is-mine="true">
                <input _ngcontent-c16="" class="form-control ng-star-inserted" id="files" name="files" ng2fileselect="" type="file" ng-reflect-uploader="[object Object]" hidden="">

                <span _ngcontent-c16="">File &lt; 3MB</span>
                <loader _ngcontent-c16="" ng-reflect-is-running="false">
                    <sk-chasing-dots _nghost-c7="" ng-reflect-delay="0" ng-reflect-color="red" ng-reflect-is-running="false">
                        <div _ngcontent-c7="" class="chasing-dots-spinner" ng-reflect-ng-class="chasing-dots-spinner" hidden="">
                            <div _ngcontent-c7="" class="dot1 ng-star-inserted" ng-reflect-ng-class="dot1" style="background-color: red;"></div>
                            <div _ngcontent-c7="" class="dot2 ng-star-inserted" ng-reflect-ng-class="dot2" style="background-color: red;"></div>
                        </div>
                    </sk-chasing-dots>
                </loader>
                <div _ngcontent-c16="" style="padding-left: 90px;">
                    <div _ngcontent-c16="" class="picture-group" ng-reflect-klass="picture-group" ng-reflect-ng-class="[object Object]">
                        <div _ngcontent-c16="" class="picture-wrapper">
                            <img _ngcontent-c16="" id="anh_minhchung" class="ng-star-inserted">
                        </div>
                        <a _ngcontent-c16="" id="thaydoi_minhchung" class="change-picture ng-star-inserted" href="#">Thay đổi minh chứng</a>
                    </div>
                </div>
            </my-image-upload>
        </div>
    </div>
</div>
<script>
    function box_upminhchung(maND,mssv) {
        //cho hiện hộp đăng nhập trong 300ms
        $('#anh_minhchung').attr('src', "/");
        $('#upminhchung').fadeIn(300);
        let data_ = "'" + maND + "','" + mssv + "'";
        $('#thaydoi_minhchung').attr("onclick", "upload(" + data_ + ")");
        // thêm phần tử id="over" vào sau body
        $('body').append('<div id="over">');
        $('#over').fadeIn(300);
        return false;
    }
    // khi click đóng hộp thoại
    $(document).on('click', "button.close, #over", function () {
        $('#over, .minhchung_box').fadeOut(300, function () {
            $('#over').remove();
        });
        return false;
    });
</script>
<script>
    function upload(maND,mssv) {
        $('#file_up').trigger('click');
        $('#file_up').change(function () {
            let data_ = "'" + maND + "','" + mssv + "'"; // để truyền vào onclick
            let formData_1 = new FormData();
            let file = document.getElementById("file_up").files[0]; // lấy ảnh từ input type="file"
            if (file == null) {
                alert("Chọn hình ảnh thất bại!");
                clearFileInput("file_up");
                $('#file_up').trigger('click');
            }
            else {
                formData_1.append("file_up", file);
                formData_1.append("name_file", maND);
                $.ajax({
                    type: "POST",
                    url: '/Upload/upLoadfile',
                    data: formData_1,
                    dataType: 'json',
                    contentType: false,
                    processData: false,
                    success: function (response) {
                        if (response.success) {
                            $('#anh_minhchung').attr("src", response.url_img + "?" + new Date().getTime());
                            $("#file_up").replaceWith("<input type='file' accept='image/*' id='file_up' style='display:none' />");
                            $('#' + maND).css('color', 'aqua');
                            var daunhay = "'";
                            $('#' + maND).attr("onclick", "show_minhchung("+data_+")");
                        }
                        else {
                            alert(response.responseText);
                        }
                    },
                    error: function (error) {
                        alert("Lỗi!!!" + error);
                    }
                });
            }
        });
    };
</script>
<script>
    function show_minhchung(maND, mssv) {
        var fromdata = new FormData();
        fromdata.append("maND_TC", maND);
        fromdata.append("maSSV", mssv);
        $.ajax({
            type: "POST",
            url: '/Upload/show_minhchung',
            data: fromdata,
            dataType: 'json',
            contentType: false,
            processData: false,
            success: function (response) {
                if (response.success) {
                    $('#anh_minhchung').attr("src", response.url_img);
                }
            },
            error: function (error) {
                alert("Lỗi!!!" + error);
            }
        });
        $('#upminhchung').fadeIn(300);
        $('#thaydoi_minhchung').attr("onclick", "upload('" + maND + "')");
        $('#anh_minhchung').attr("src", "/")
        // khi click đóng hộp thoại
        $(document).on('click', "button.close, #over", function () {
            $('#over, .minhchung_box').fadeOut(300, function () {
                $('#over').remove();
            });
            return false;
        });
    }
</script>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
<link href="~/Content/css/upminhchung.css" rel="stylesheet" />