Edu_Hutech/Controllers/PhongController.cs
using Edu_Hutech.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Edu_Hutech.Controllers
{
    public class PhongController : Controller
    {
        // GET: Phong
        HutechEduDataContext db = new HutechEduDataContext();
        public ActionResult Phong()
        {
            if (Session["TaiKhoan_Phong"] == null)
            {
                return RedirectToAction("UserLogin", "UserLogin");
            }
            return View();
        }
        [HttpPost]
        public ActionResult ThoiGian_DangKy()
        {
            return PartialView();
        }
        public JsonResult Capnhat_Thoigiandangky(String maHD, DateTime ngayBD,DateTime ngayKT)
        {
            if (ngayBD.CompareTo(ngayKT) < 0 || ngayBD.CompareTo(ngayKT) == 0 )
            {
                db.ThoiGian_DangKy_PhongTrao(maHD, ngayBD, ngayKT);
                return Json(new { success = true, mess = "Thành công!" }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false, mess = "Ngày kết thúc phải sau ngày bắt đầu!" }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult Danhsach_dk_sv5t_tr_th_tw()
        {
            var ds = db.DSach_DK_SV5T_Cap_TR_TH_TW().ToList();
            return View(ds);
        }
        public ActionResult dsach_sv_dk_theo_khoa_cap(String maKhoa, String maCap)
        {   
            var ds = db.DSach_DK_SV5T_TheoKhoa_Cap(maKhoa, maCap,1,10).ToList();
            return PartialView(ds);
        }
        public ActionResult danhgia_chitiet_sv(long maPDK, string macap)
        {
            string tai_khoan = System.Web.HttpContext.Current.Session["TaiKhoan_Phong"].ToString() ;
            var list_tc = db.GetTaiLieu_SV5T_TheoCap(macap).ToList();
            // luu tiêu chí vào bảng dánh giá của admin với tình trạng là fasle
            var kt_maPDK_2 = db.KQ_DanhGiaND_SV5T_Admins.Where(s => s.MaPDK_SV5T == maPDK).Select(s => s.Dat).FirstOrDefault();
            if (kt_maPDK_2 == null)
            {
                foreach (var item in list_tc)
                {
                    db.Add_KQ_DanhGia_Sv5t_admin(tai_khoan, item.Ma_NDTieuChi, maPDK);
                }
            }
            //lay danh sach tieu chi theo maPDK( ten, ma, tinh trang minh chung, đạt hay chưa??)
            var ds = db.DSach_TC_Theo_MaPDK(maPDK).ToList();
            System.Web.HttpContext.Current.Session["maPDK"] = maPDK; // lưu lại để chỉnh sửa trạng thái ở KQ_DanhGiaND_SV5T_Admin
            return View(ds);
        }
        [HttpPost]
        public ActionResult QuanLyTieuChi(string ma_phancap)
        {
            if (Session["TaiKhoan_Phong"] == null)
            {
                return RedirectToAction("UserLogin", "UserLogin");
            }
            List<object> list = new List<object>();

            ViewBag.bien = ma_phancap;
            var ds = db.TieuChis.Where(a => a.MaPhanCap == ma_phancap).Select(a => a).OrderByDescending(a => a.Ma_NDTieuChi).ToList();
            list.Add(db.TieuChuans.ToList());
            if(ds.Count == 0)
            {
                list.Add(db.TieuChis.Where(a => a.MaPhanCap != "LHTT").Select(a => a).OrderByDescending(a => a.Ma_NDTieuChi).ToList());
            }
            else
            {
                list.Add(db.TieuChis.Where(a => a.MaPhanCap == ma_phancap).Select(a => a).OrderByDescending(a => a.Ma_NDTieuChi).ToList());
            }
            return PartialView(list);
        }

        public ActionResult Create()
        {
            var ma_tchuan = System.Web.HttpContext.Current.Request.Params["ma_tieuchuan"];
            var ten_tieuchi = System.Web.HttpContext.Current.Request.Params["ten_tieuchi"];
            var diem = System.Web.HttpContext.Current.Request.Params["diem"];
            var khoa = Boolean.Parse(System.Web.HttpContext.Current.Request.Params["khoa"]);
            var truong = Boolean.Parse(System.Web.HttpContext.Current.Request.Params["truong"]);
            var thanh = Boolean.Parse(System.Web.HttpContext.Current.Request.Params["thanh"]);
            var trunguong = Boolean.Parse(System.Web.HttpContext.Current.Request.Params["trunguong"]);
            var batbuoc = Boolean.Parse(System.Web.HttpContext.Current.Request.Params["batbuoc"]);
            var ma_phancap = System.Web.HttpContext.Current.Request.Params["ma_phancap"];

            if(diem == null)
            {
                diem = "0";
            }

            List<TieuChi> tc_list = new List<TieuChi>();
            TieuChi tc = new TieuChi();

            if(ma_phancap == "LHTT")
            {
                var tieuchi = db.TieuChis.Where(a => a.MaPhanCap == "LHTT").OrderByDescending(a => a.Ma_NDTieuChi).FirstOrDefault().Ma_NDTieuChi;
                char[] tam = tieuchi.ToCharArray();
                int stt = int.Parse(tam[tam.Count() - 1].ToString()) + 1;

                tc.MaPhanCap = "LHTT";
                tc.Diem = float.Parse(diem);
                tc.MaTieuChi = ma_tchuan;
                tc.Ma_NDTieuChi = ma_tchuan + stt;
                tc.TenNDTieuChi = ten_tieuchi;
                tc.MaTieuChi = ma_tchuan;
                tc_list.Add(tc);

                db.TieuChis.InsertAllOnSubmit(tc_list);
                db.SubmitChanges();

                return Json(new { success = true, mess = "Thêm mới thành công!" }, JsonRequestBehavior.AllowGet);
            }
            else if(ma_phancap == "SV5T")
            {
                var tam = db.PhanCap_TieuChis.Where(a => (a.Khoa == khoa) && (a.Truong == truong) && (a.Thanh == thanh) && (a.TrungUong == trunguong)).Select(a => a.MaPhanCap).FirstOrDefault();
                if(tam.Count() == 0)
                {
                    khoa = true;
                }
                tc.MaPhanCap = db.PhanCap_TieuChis.Where(a => (a.Khoa == khoa) && (a.Truong == truong) && (a.Thanh == thanh) && (a.TrungUong == trunguong)).Select(a => a.MaPhanCap).FirstOrDefault();
                tc.Diem = float.Parse(diem);
                tc.MaTieuChi = ma_tchuan;

                var tieuchi = db.TieuChis.Where(a => a.MaTieuChi == ma_tchuan).OrderByDescending(a => a.Ma_NDTieuChi).FirstOrDefault().Ma_NDTieuChi;
                char[] abc = tieuchi.ToCharArray();
                int stt = int.Parse(abc[abc.Count() - 1].ToString()) + 1;

                tc.Ma_NDTieuChi = "SV" + ma_tchuan + stt;
                tc.TenNDTieuChi = ten_tieuchi;

                tc_list.Add(tc);

                db.TieuChis.InsertAllOnSubmit(tc_list);
                db.SubmitChanges();

                return Json(new { success = true, mess = "Thêm mới thành công!" }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { success = false, mess = "Thêm mới thành công!" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Edu_Hutech/Views/Phong/Create.cshtml
@model IEnumerable<object>

@{ 
    List<Edu_Hutech.Models.TieuChi> tchi = Model.ToList()[0] as List<Edu_Hutech.Models.TieuChi>;
    List<Edu_Hutech.Models.TieuChuan> tchuan = Model.ToList()[1] as List<Edu_Hutech.Models.TieuChuan>;
}

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPhong.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4> Tiêu chí: </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
       <label for="username"> Tên tiêu chuẩn: </label>
       <select name="ma_tieuchuan">
           @foreach(var item in tchuan)
           {
               <option value="@item.MaTieuChi">@item.TenTieuChi</option>
           }
       </select>

        <label for="username"> Tên tiêu chí: </label>
        <input style="margin-left:10px; padding-top:5px" name="ten_tieuchi" placeholder="Tên tiêu chí" type="text" id="ten_tieuchi" required oninvalid="this.setCustomValidity('Hãy nhập tên tiêu chí!')" oninput="setCustomValidity('')" />
        
        <label for="username"> Điểm: </label>
        <input style="margin-left:10px; padding-top:5px" name="diem" placeholder="Tên Đề Tài" type="number" min="0" id="diem" />
        
        <label for="username"> Cấp tiêu chí: </label>
        
        <input type="checkbox" name="khoa" value="Khoa"/>
        <input type="checkbox" name="truong" value="Trường"/>
        <input type="checkbox" name="thanh" value="Thành"/>
        <input type="checkbox" name="trunguong" value="Trung Ương"/>
        <input type="checkbox" name="batbuoc" value="Bắt Buộc"/>
        <input type="checkbox" name="lhtt" value="Lớp học tiên tiến"/>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Edu_Hutech/Views/Phong/Danhsach_dk_sv5t_tr_th_tw.cshtml
@{
    ViewBag.Title = "Danhsach_dk_sv5t_tr_th_tw";
    Layout = "~/Views/Shared/_LayoutPhong.cshtml";
}
@model IEnumerable<Edu_Hutech.Models.DSach_DK_SV5T_Cap_TR_TH_TWResult>
<p></p>
<div class="input-group">
    <select id="khoa">
        @foreach (var item in Model)
        {
            <option value="@item.MaKhoa">@item.MaKhoa</option>
        }
    </select>
    <select id="macap">
        <option value="TR">Trường</option>
        <option value="TH">Thành</option>
        <option value="TW">Trung Ương</option>
    </select>
    <a href="#" onclick="load_ds()">
        <i class="fa fa-refresh fa-spin" style="font-size:24px"></i>
    </a>
</div>
<table>
    <tr>
        <th>Họ Tên</th>
        <th>Mã Số Sinh Viên</th>
        <th>Tình Trang</th>
    </tr>
    <tr id="ds_dk_sv5t"></tr>
</table>
<p id="thong_bao"></p>
<script>
    function load_ds() {
        var malop = $('#khoa').val();
        var macap = $('#macap').val();
        $.ajax({
            type: "post",
            url: '@Url.Action("dsach_sv_dk_theo_khoa_cap", "Phong")',
            data: {
                maKhoa: malop,
                maCap: macap,
            },
            success: function (a) {
                if (a.success == true) {
                    alert("Không có sinh viên nào được chọn!!!");
                }
                else
                    $('#ds_dk_sv5t').html(a);
            },
            error: function (jqXHR, textStatus, errorThrown) {
                alert(errorThrown)
            },
        });
    }
    window.onload = load_ds;
</script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>

Edu_Hutech/Views/Phong/Phong.cshtml
@{
    ViewBag.Title = "Phong";
    Layout = "~/Views/Shared/_LayoutPhong.cshtml";
}
<h2>View tài khoản Phòng </h2>
<h3>
    Chức năng:
</h3>
<a style="font-size:20px" href="@Url.Action("Danhsach_dk_sv5t_tr_th_tw","Phong")">Đánh giá sinh viên 5 tốt</a>
<br />
<a style="font-size:20px" href="#" onclick="thoigian_dangky()">Thời Gian Đăng Ký Các Hoạt Động</a>

<div id="ds_tieuchi"></div>
<div id="thoigian_dangky"></div>
<script>
    function thoigian_dangky() {
        $.ajax({
            type: 'post',
            url: '@Url.Action("ThoiGian_DangKy","Phong")',
            data: null,
            success: function (a) {
                $("#thoigian_dangky").html(a);
            }
        });
    }
</script>

Edu_Hutech/Views/Phong/QuanLyTieuChi.cshtml
@model IEnumerable<object>

@{
    List<Edu_Hutech.Models.TieuChuan> tchuan = Model.ToList()[0] as List<Edu_Hutech.Models.TieuChuan>;
    List<Edu_Hutech.Models.TieuChi> tchi = Model.ToList()[1] as List<Edu_Hutech.Models.TieuChi>;
}


<h2>QuanLyTieuChi</h2>

<p style="font-weight:bold; color:initial" onclick="box_upminhchung('@ViewBag.bien')"> Tạo mới </p>
<table class="table">
    <tr>
        <th>
            Tiêu chuẩn:
        </th>
        <th>
            Tên tiêu chí:
        </th>
        <th>
            Điểm:
        </th>
        <th></th>
    </tr>

    @foreach (var item in tchi)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MaTieuChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TenNDTieuChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Diem)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Ma_NDTieuChi }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Ma_NDTieuChi })
            </td>
        </tr>
    }

</table>

<div style="top:0" class="minhchung_box" id="upminhchung">
    <div _ngcontent-c15="" class="modal-content text-center">
        <div _ngcontent-c15="" class="modal-header">
            <h4 _ngcontent-c15="" class="modal-title">Thêm tài khoản mới</h4>
            <button _ngcontent-c15="" aria-label="Close" class="close">
                <span _ngcontent-c15="" aria-hidden="true">×</span>
            </button>
        </div>
        <div _ngcontent-c15="" class="modal-body">
            <my-image-upload _ngcontent-c15="" _nghost-c16="" ng-reflect-is-mine="true">
                <label for="username"> Tên tiêu chuẩn: </label>
                <select name="ma_tieuchuan">
                    @foreach (var item in tchuan)
                    {
                        <option value="@item.MaTieuChi">@item.TenTieuChi</option>
                    }
                </select>
                <br />
                <label for="username"> Tên tiêu chí: </label>
                <input style="margin-left:10px; padding-top:5px" name="ten_tieuchi" placeholder="Tên tiêu chí" type="text" id="ten_tieuchi" required oninvalid="this.setCustomValidity('Hãy nhập tên tiêu chí!')" oninput="setCustomValidity('')" />
                <br />
                <label for="username"> Điểm: </label>
                <input style="margin-left:10px; padding-top:5px" name="diem" placeholder="Tên Đề Tài" type="number" min="0" id="diem" />
                <br />
                <br />
                <label for="username"> Cấp tiêu chí: </label>
                <br />
                <div id="phancap_sv5t">
                    <label for="username"> Khoa: </label>
                    <input type="checkbox" id="khoa" name="khoa" value="Khoa" />
                    <br />
                    <label for="username"> Trường: </label>
                    <input type="checkbox" id="truong" name="truong" value="Trường" />
                    <br />
                    <label for="username"> Thành: </label>
                    <input type="checkbox" id="thanh" name="thanh" value="Thành" />
                    <br />
                    <label for="username"> Trung ương: </label>
                    <input type="checkbox" id="trunguong" name="trunguong" value="Trung Ương" />
                    <br />
                    <label for="username"> Bắt buộc: </label>
                    <input type="checkbox" id="batbuoc" name="batbuoc" value="Bắt Buộc" />
                </div>
            </my-image-upload>
            <br />
            <div class="input-group" style="padding-top:20px">
                <a _ngcontent-c16="" id="Create" class="change-picture ng-star-inserted" href="#">Thêm mới</a>
            </div>
        </div>
    </div>
</div>

<script>
    function box_upminhchung(ma_phancap) {
        //cho hiện hộp đăng nhập trong 300ms
        if (ma_phancap == "SV5T")
        {
            $('#phancap_sv5t').css('display', 'block');
        } else {
            $('#phancap_sv5t').css('display', 'none');
        }
        $('#anh_minhchung').attr('src', "/");
        $('#upminhchung').fadeIn(300);
        // thêm phần tử id="over" vào sau body
        $('body').append('<div id="over">');
        $('#Create').attr("onclick", "themmoi('" + ma_phancap + "')");
        $('#over').fadeIn(300);
        return false;
    }
    // khi click đóng hộp thoại
    $(document).on('click', "button.close, #over", function () {
        $('#over, .minhchung_box').fadeOut(300, function () {
            $('#over').remove();
        });
        return false;
    });
</script>
<script>
    function themmoi(ma_phancap) {
        var ma_tieuchuan = $('#ma_tieuchuan').val();
        var ten_tieuchi = $('#ten_tieuchi').val();
        var diem = $('#diem').val();
        var khoa = $('#khoa').is(":checked");
        var truong = $('#truong').is(":checked");
        var thanh = $('#thanh').is(":checked");
        var trunguong = $('#trunguong').is(":checked");
        var batbuoc = $('#batbuoc').is(":checked");
        var form_data = new FormData();
        form_data.append("ma_tieuchuan", ma_tieuchuan);
        form_data.append("ten_tieuchi", ten_tieuchi);
        form_data.append("diem", diem);
        form_data.append("khoa", khoa);
        form_data.append("truong", truong);
        form_data.append("thanh", thanh);
        form_data.append("trunguong", trunguong);
        form_data.append("batbuoc", batbuoc);
        form_data.append("ma_phancap", ma_phancap);

        $.ajax({
            type: "POST",
            url: '/Phong/Create',
            data: form_data,
            dataType: 'json',
            contentType: false,
            processData: false,
            success: function (response) {
                if (response.success) {
                    $('#over, .minhchung_box').fadeOut(300, function () {
                        $('#over').remove();
                    });
                    alert("Đã thêm thành công");
                    if (ma_phancap == "LHTT") {
                        $('#LHTT').click();
                    } else {
                        $('#SV5T').click();
                    }
                }
                else {
                    alert(response.mess);
                }
            },
            error: function (error) {
                alert("Lỗi!!!" + error);
            }
        })
    }
</script>
<link href="~/Content/css/upminhchung.css" rel="stylesheet" />

Edu_Hutech/Views/Phong/ThoiGian_DangKy.cshtml
<div id="thoigian_dangky"></div>
<table>
    <tr>
        <th>Hoạt Động</th>
        <td>Ngày Bắt Đầu</td>
        <td>Ngày Kết Thúc</td>
        <td></td>
    </tr>
    <tr>
        <td>
            <select id="hoatdong">
                <option value="SV5T">Sinh Viên Năm Tốt</option>
                <option value="NCKH">Nghiên Cứu Khoa Học</option>
                <option value="LHTT">Lớp Học Tiên Tiến</option>
            </select>
        </td>
        <td>
            <input id="ngaybd" type="date" required />
        </td>
        <td>
            <input id="ngaykt" type="date" required />
        </td>
        <td><button onclick="luu()">Lưu</button></td>
    </tr>
</table>
<script>
    function luu() {
        var mahd = $("#hoatdong").val();
        var ngaybd = $("#ngaybd").val();
        var ngaykt = $("#ngaykt").val();
        $.ajax({
            type: 'post',
            url: '@Url.Action("Capnhat_Thoigiandangky","Phong")',
            data: {
                maHD: mahd,
                ngayBD: ngaybd,
                ngayKT: ngaykt
            },
            dataType: 'json',
            success: function (a) {
                if (a.success) {
                    alert(a.mess);
                }
                else {
                    alert(a.mess)
                }
            },
        });
    }
</script>

Edu_Hutech/Views/Phong/dsach_sv_dk_theo_khoa_cap.cshtml
@model IEnumerable<Edu_Hutech.Models.DSach_DK_SV5T_TheoKhoa_CapResult>
@foreach (var item in Model)
{
    <td>@item.Ho @item.Ten</td>
    <td>@item.MSSV</td>
    <td><a id="danhgia" onclick="truyen_mssv(@item.MSSV)" href="@Url.Action("danhgia_chitiet_sv","Phong",new { maPDK = item.MaPDK_SV5T, macap = item.MaCap })" target="_blank" style="color:red">Đánh Giá</a></td>
}

<script>
    localStorage.clear();
</script>
<script>
    //dung de load minh chung cho sv duoc chon
    function truyen_mssv(mssv) {
        localStorage.setItem("MSSV", mssv);
    }
</script>